# Use Dockerized infrastructure
sudo: false

# Use node_js environnement
language: node_js
node_js:
  - "6"

# Cache Gcloud SDK between commands
cache:
  yarn: true
  directories:
  - "$HOME/google-cloud-sdk/"

env:
  global:


install:
  - cd hello-world && npm install && cd -

script:
  - cd hello-world && npm test && cd -

before_deploy:
  - npm install -g serverless
  - serverless --version

  # use the decrypted service account credentials to authenticate the command line tool
  # get the encrypted variable names from travis cli: https://docs.travis-ci.com/user/encrypting-files/
  - openssl aes-256-cbc -K $encrypted_ec542ec26cc7_key -iv $encrypted_ec542ec26cc7_iv -in goog-caseywest-7fd69b9aa3b0.json.enc -out goog-caseywest-7fd69b9aa3b0.json -d

deploy:
  - provider: script
    script:
      - cd hello-world && serverless deploy && cd -
    skip_cleanup: true
    on:
      branch: master

